總結
* 如果是要縮小圖片的話，通常 INTER_AREA 使用效果較佳。
* 如果是要放大圖片的話，通常 INTER_CUBIC 使用效果較佳，次等則是 INTER_LINEAR。
* 如果要追求速度的話，通常使用 INTER_NEAREST。
* 由快到慢排序：INTER_NEAREST > INTER_CUBIC > INTER_LINEAR > INTER_AREA > INTER_LANCZOS4

In [2]:
import cv2
import numpy as np
import sys

In [15]:
def scaling(img_path): #影像縮放方法
	
	img = cv2.imread(img_path)

	if img is None:
		sys.exit("無法讀取影像...")

	#影像放大
	#方法1
	res = cv2.resize(img,None,fx=1.5, fy=1.5, interpolation = cv2.INTER_CUBIC	) #	cv2.INTER_CUBIC 4x4像素鄰域的雙三次插值
	
	#方法2
	height, width = img.shape[:2]
	res2 = cv2.resize(img,(2*width, 2*height), interpolation = cv2.INTER_CUBIC	)
	print(img.shape)
	cv2.imshow('res',res)
	cv2.imshow('res2',res2)
	
	k = cv2.waitKey(0)
	cv2.destroyAllWindows() 

#放大
scaling("data/tennis.jpg")


(315, 512, 3)


In [26]:
def translation(img_path): #平移
	
	img = cv2.imread(img_path)

	if img is None:
		sys.exit("無法讀取影像...")

	#影像平移
	rows,cols = img.shape[:2] 
    #記得width = columns ;height = rows 避免混淆
	#[1,0,tx]
	#[0,1,yx]
	M = np.float32([[1,0,100],[0,1,100]]) #M 矩陣
	dst = cv2.warpAffine(img,M,(cols,rows)) #平移計算
	
	cv2.imshow('dst',dst)
	k = cv2.waitKey(0)
	cv2.destroyAllWindows() 
    
#平移
translation("data/tennis.jpg")


In [27]:
def rotation(img_path): #旋轉
	
	img = cv2.imread(img_path)

	if img is None:
		sys.exit("無法讀取影像...")

	#影像旋轉
	rows,cols = img.shape[:2] 
	#來計算旋轉角度θ,我們要提供個旋轉矩陣
	#OpenCV提供了可以任意旋轉縮放與不同中心點的旋轉
	# cols-1 和 rows-1 找出影像中心點做旋轉
	M = cv2.getRotationMatrix2D(((cols-1)/2.0,(rows-1)/2.0),45,1) #計算旋轉矩陣;getRotationMatrix2D(rx,ry,θ,scale)
	print("M旋轉矩陣:",M)
	dst = cv2.warpAffine(img,M,(cols,rows))
	
	cv2.imshow('dst',dst)
	
	k = cv2.waitKey(0)
	cv2.destroyAllWindows()

#旋轉
rotation("data/tennis.jpg")

M旋轉矩陣: [[  0.70710678   0.70710678 -36.18154724]
 [ -0.70710678   0.70710678 226.65001795]]


In [28]:
def affine_transformation(img_path): #任意映射轉換
	
	img = cv2.imread(img_path)

	if img is None:
		sys.exit("無法讀取影像...")

	#影像任意點映射
	rows,cols = img.shape[:2] 
	pts1 = np.float32([[50,50],[200,50],[50,200]]) #原圖這三個座標點位置
	pts2 = np.float32([[10,100],[200,50],[100,250]]) #映射轉換後的座標點位置,(50,50)->(10,100)
	M = cv2.getAffineTransform(pts1,pts2)
	print(M)
	#投影轉換
	dst = cv2.warpAffine(img,M,(cols,rows))

	
	cv2.imshow('Input',img)
	cv2.imshow('Output',dst)
	
	k = cv2.waitKey(0)
	cv2.destroyAllWindows()
#映射變形
affine_transformation("data/tennis.jpg")


[[  1.26666667   0.6        -83.33333333]
 [ -0.33333333   1.          66.66666667]]


In [42]:
def perspective_transformation(img_path): #透視轉換變形
	
	img = cv2.imread(img_path)

	if img is None:
		sys.exit("無法讀取影像...")

	#影像透視點轉換變形
	rows,cols = img.shape[:2] 
	#提供至少4個座標點來計算3x3的透視轉換矩陣
	pts1 = np.float32([[28,157],[48,152],[250,258],[308,251]]) #斜圖的[左上,右上,左下,右下]
	pts2 = np.float32([[0,0],[100,0],[0,313],[100,313]]) #想擺正圖的[左上,右上,左下,右下]
	
	#計算3x3矩陣轉換,將場內線轉換成水平直線
	M = cv2.getPerspectiveTransform(pts1,pts2)
	#透視轉換
	dst = cv2.warpPerspective(img,M,(100,313))
    
	print(M)

	cv2.imshow('Input',img)
	cv2.imshow('Output',dst)
	
	k = cv2.waitKey(0)
	cv2.destroyAllWindows()

#透視轉換
perspective_transformation("data/tennis.jpg")

[[-2.04502930e+01  4.49501489e+01 -6.48456518e+03]
 [-7.16067675e+00 -2.86427070e+01  4.69740395e+03]
 [-1.70109968e-02 -4.29015671e-02  1.00000000e+00]]
